name: "CI"

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
      - "staging"
      - "staging-blast"

jobs:
  lint:
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-lint.yml@ci/proper-cache"

  build:
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-build.yml@ci/proper-cache"

  test-bulloak:
    needs: ["lint", "build"]
    if: needs.build.outputs.cache-hit != 'true'
    uses: "sablier-labs/reusable-workflows/.github/workflows/bulloak-check.yml@ci/proper-cache"
    with:
      skip-modifiers: true
      tree-path: "tests"

  test-unit:
    needs: ["lint", "build"]
    if: needs.build.outputs.cache-hit != 'true'
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-test.yml@ci/proper-cache"
    with:
      foundry-fuzz-runs: 2000
      foundry-profile: "test-optimized"
      match-path: "tests/unit/**/*.sol"
      name: "Unit tests"

  test-integration:
    needs: ["lint", "build"]
    if: needs.build.outputs.cache-hit != 'true'
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-test.yml@ci/proper-cache"
    with:
      foundry-fuzz-runs: 2000
      foundry-profile: "test-optimized"
      match-path: "tests/integration/**/*.sol"
      name: "Integration tests"

  test-invariant:
    needs: ["lint", "build"]
    if: needs.build.outputs.cache-hit != 'true'
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-test.yml@ci/proper-cache"
    with:
      foundry-profile: "test-optimized"
      match-path: "tests/invariant/**/*.sol"
      name: "Invariant tests"

  test-fork:
    needs: ["lint", "build"]
    if: needs.build.outputs.cache-hit != 'true'
    secrets:
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-test.yml@ci/proper-cache"
    with:
      foundry-fuzz-runs: 20
      foundry-profile: "test-optimized"
      match-path: "tests/fork/**/*.sol"
      name: "Fork tests"

  coverage:
    needs: ["lint", "build"]
    if: needs.build.outputs.cache-hit != 'true'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-coverage.yml@ci/proper-cache"
    with:
      match-path: "tests/{fork,integration,unit}/**/*.sol"
